# Generated by Django 3.0.2 on 2020-01-27 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('rack_u', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=10)),
                ('height', models.PositiveIntegerField()),
                ('display_color', models.CharField(default='777777', max_length=6)),
                ('ethernet_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('power_ports', models.PositiveIntegerField(blank=True, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50)),
                ('memory', models.PositiveIntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.CharField(max_length=5)),
                ('u1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance1', to='ass_man.Instance')),
                ('u10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance10', to='ass_man.Instance')),
                ('u11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance11', to='ass_man.Instance')),
                ('u12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance12', to='ass_man.Instance')),
                ('u13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance13', to='ass_man.Instance')),
                ('u14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance14', to='ass_man.Instance')),
                ('u15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance15', to='ass_man.Instance')),
                ('u16', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance16', to='ass_man.Instance')),
                ('u17', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance17', to='ass_man.Instance')),
                ('u18', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance18', to='ass_man.Instance')),
                ('u19', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance19', to='ass_man.Instance')),
                ('u2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance2', to='ass_man.Instance')),
                ('u20', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance20', to='ass_man.Instance')),
                ('u21', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance21', to='ass_man.Instance')),
                ('u22', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance22', to='ass_man.Instance')),
                ('u23', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance23', to='ass_man.Instance')),
                ('u24', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance24', to='ass_man.Instance')),
                ('u25', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance25', to='ass_man.Instance')),
                ('u26', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance26', to='ass_man.Instance')),
                ('u27', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance27', to='ass_man.Instance')),
                ('u28', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance28', to='ass_man.Instance')),
                ('u29', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance29', to='ass_man.Instance')),
                ('u3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance3', to='ass_man.Instance')),
                ('u30', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance30', to='ass_man.Instance')),
                ('u31', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance31', to='ass_man.Instance')),
                ('u32', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance32', to='ass_man.Instance')),
                ('u33', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance33', to='ass_man.Instance')),
                ('u34', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance34', to='ass_man.Instance')),
                ('u35', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance35', to='ass_man.Instance')),
                ('u36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance36', to='ass_man.Instance')),
                ('u37', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance37', to='ass_man.Instance')),
                ('u38', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance38', to='ass_man.Instance')),
                ('u39', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance39', to='ass_man.Instance')),
                ('u4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance4', to='ass_man.Instance')),
                ('u40', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance40', to='ass_man.Instance')),
                ('u41', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance41', to='ass_man.Instance')),
                ('u42', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance42', to='ass_man.Instance')),
                ('u5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance5', to='ass_man.Instance')),
                ('u6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance6', to='ass_man.Instance')),
                ('u7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance7', to='ass_man.Instance')),
                ('u8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance8', to='ass_man.Instance')),
                ('u9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance9', to='ass_man.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Model'),
        ),
        migrations.AddField(
            model_name='instance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Rack'),
        ),
    ]
