# Generated by Django 3.0.2 on 2020-01-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='cpu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='display_color',
            field=models.CharField(blank=True, default='yellow', max_length=50),
        ),
        migrations.AddField(
            model_name='model',
            name='ethernet_ports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='memory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='model_number',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='power_ports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='storage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.CharField(max_length=50),
        ),
    ]
