# Generated by Django 3.0.2 on 2020-02-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0003_auto_20200212_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='datacenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
        ),
    ]
