# Generated by Django 3.0.2 on 2020-02-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0004_auto_20200213_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_port',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='power_port',
            name='pdu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ass_man.PDU'),
        ),
    ]
