# Generated by Django 3.0.2 on 2020-01-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0005_auto_20200120_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='u10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance10', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance11', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance12', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance13', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance14', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance15', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance16', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance17', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance18', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance19', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance20', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance21', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance22', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance23', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance24', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance25', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance26', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance27', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance28', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance29', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance30', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance31', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u32',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance32', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u33',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance33', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u34',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance34', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u35',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance35', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u36',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance36', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u37',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance37', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u38',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance38', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u39',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance39', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance4', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u40',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance40', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u41',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance41', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u42',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance42', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance5', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance6', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance7', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance8', to='ass_man.Instance'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance9', to='ass_man.Instance'),
        ),
    ]
