# Generated by Django 3.0.2 on 2020-02-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0005_auto_20200216_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='datacenter',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='datacenter',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='pdu_l',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, related_name='pdu_l', to='ass_man.PDU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rack',
            name='pdu_r',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, related_name='pdu_r', to='ass_man.PDU'),
            preserve_default=False,
        ),
    ]
