# Generated by Django 3.0.2 on 2020-01-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0006_auto_20200120_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_man.Rack'),
        ),
    ]
