# Generated by Django 3.0.2 on 2020-01-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0007_auto_20200120_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
