# Generated by Django 3.0.2 on 2020-02-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0007_auto_20200217_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_avail', models.PositiveIntegerField()),
            ],
        ),
    ]
