# Generated by Django 3.0.2 on 2020-02-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0008_asset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='network_ports_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
