# Generated by Django 3.0.2 on 2020-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0009_auto_20200121_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model',
            name='model_number',
            field=models.CharField(default='B1', max_length=5),
            preserve_default=False,
        ),
    ]
