# Generated by Django 3.0.2 on 2020-01-24 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ass_man', '0010_auto_20200124_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='display_color',
        ),
        migrations.AlterField(
            model_name='instance',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Model'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Rack'),
        ),
        migrations.AlterField(
            model_name='model',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
