# Generated by Django 3.0.2 on 2020-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0010_pdu_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_port',
            name='name',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
