# Generated by Django 3.0.2 on 2020-01-24 03:42

import ass_man.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0011_auto_20200124_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='display_color',
            field=models.CharField(default='777777', max_length=6, validators=[ass_man.validators.validate_color, django.core.validators.MinLengthValidator(6)]),
        ),
    ]
