# Generated by Django 3.0.3 on 2020-03-04 19:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0012_auto_20200225_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decommissioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('asset_state', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('network_graph', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
