# Generated by Django 3.0.2 on 2020-01-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0012_model_display_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_number',
            field=models.CharField(max_length=10),
        ),
    ]
