# Generated by Django 3.0.3 on 2020-03-02 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0012_auto_20200225_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.PositiveIntegerField(blank=True, default=100000, validators=[django.core.validators.RegexValidator('\\d{6,6}', 'Number must be 11 digits', 'Invalid number')]),
        ),
    ]
