# Generated by Django 3.0.3 on 2020-03-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0012_auto_20200225_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_port',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Asset'),
        ),
    ]
