# Generated by Django 3.0.2 on 2020-01-24 04:15

import ass_man.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0013_auto_20200124_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=20, validators=[ass_man.validators.validate_hostname]),
        ),
    ]
