# Generated by Django 3.0.2 on 2020-01-24 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0014_auto_20200124_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='rack_u',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
