# Generated by Django 3.0.3 on 2020-03-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0014_auto_20200327_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_port',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
