# Generated by Django 3.0.2 on 2020-01-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0015_auto_20200124_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='rack_number',
        ),
    ]
