# Generated by Django 3.0.3 on 2020-03-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0013_decommissioned'),
        ('ass_man', '0015_auto_20200327_2245'),
    ]

    operations = [
    ]
