# Generated by Django 3.0.3 on 2020-03-30 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0016_permission_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.PositiveIntegerField(blank=True, default=100000, validators=[django.core.validators.RegexValidator('\\^[0-9]{1,6}$', 'Number must be 6 digits', 'Invalid number')]),
        ),
    ]
