# Generated by Django 3.0.2 on 2020-01-25 04:44

import ass_man.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0016_remove_rack_rack_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(default='Z10', max_length=4, validators=[ass_man.validators.validate_rack_number]),
            preserve_default=False,
        ),
    ]
