# Generated by Django 3.0.2 on 2020-01-25 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0017_rack_rack_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?![0-9]+$)(?!-)[a-zA-Z0-9-]{,63}(?<!-)$')]),
        ),
    ]
