# Generated by Django 3.0.2 on 2020-01-25 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0018_auto_20200125_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid hostname as per RFC 1034.', regex='^(?![0-9]+$)(?!-)[a-zA-Z0-9-]{,63}(?<!-)$')]),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid rack number (e.g. "B12" ', regex='^[A-Z][0-9]*')]),
        ),
    ]
