# Generated by Django 3.0.3 on 2020-03-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0016_merge_20200328_2230'),
        ('ass_man', '0019_auto_20200330_0814'),
    ]

    operations = [
    ]
