# Generated by Django 3.0.3 on 2020-04-07 21:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ass_man', '0020_merge_20200330_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.AddField(
            model_name='asset',
            name='allassets_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ass_man.AllAssets'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BladeServer',
            fields=[
                ('allassets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ass_man.AllAssets')),
                ('hostname', models.CharField(blank=True, max_length=64, null=True)),
                ('slot_number', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('asset_number', models.PositiveIntegerField(blank=True, default=100000, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Number must be 6 digits', 'Invalid Number')])),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Asset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ass_man.Model')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ass_man.allassets',),
        ),
    ]
