# Generated by Django 3.0.3 on 2020-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0020_merge_20200330_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='mount_type',
            field=models.CharField(default='normal', max_length=20),
            preserve_default=False,
        ),
    ]
