# Generated by Django 3.0.2 on 2020-01-25 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0020_auto_20200125_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid rack number (e.g. "B12"). ', regex='^[A-Z][0-9]+$')]),
        ),
    ]
