# Generated by Django 3.0.3 on 2020-04-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0021_model_mount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Rack'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rack_u',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
