# Generated by Django 3.0.2 on 2020-01-25 05:30

import ass_man.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0021_auto_20200125_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=20, validators=[ass_man.validators.validate_hostname]),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=4),
        ),
    ]
