# Generated by Django 3.0.3 on 2020-04-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0021_model_mount_type'),
        ('ass_man', '0021_auto_20200407_2155'),
    ]

    operations = [
    ]
