# Generated by Django 3.0.2 on 2020-01-25 19:59

import ass_man.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0022_auto_20200125_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=5, validators=[ass_man.validators.validate_rack_number]),
        ),
    ]
