# Generated by Django 3.0.3 on 2020-04-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0022_auto_20200413_1135'),
        ('ass_man', '0022_merge_20200407_2207'),
    ]

    operations = [
    ]
