# Generated by Django 3.0.2 on 2020-01-25 20:03

import ass_man.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0023_auto_20200125_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64, validators=[ass_man.validators.validate_hostname]),
        ),
    ]
