# Generated by Django 3.0.3 on 2020-04-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0024_auto_20200417_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bladeserver',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
        ),
        migrations.AlterField(
            model_name='bladeserver',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Asset'),
        ),
        migrations.AlterField(
            model_name='bladeserver',
            name='slot_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
