# Generated by Django 3.0.2 on 2020-01-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0024_auto_20200125_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='display_color',
            field=models.CharField(default='777777', max_length=6),
        ),
    ]
