# Generated by Django 3.0.2 on 2020-01-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0025_auto_20200125_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='instance',
            name='rack_u',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(max_length=5),
        ),
    ]
