# Generated by Django 3.0.2 on 2020-01-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0028_auto_20200126_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='display_color',
            field=models.CharField(blank=True, default='777777', max_length=6),
        ),
    ]
