# Generated by Django 3.0.2 on 2020-01-19 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ass_man', '0003_auto_20200119_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('rack', models.CharField(max_length=4)),
                ('rack_u', models.PositiveIntegerField()),
                ('comment', models.TextField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_man.Model')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
