# Generated by Django 3.0.2 on 2020-01-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0008_delete_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='display_color',
            field=models.CharField(default='yellow', max_length=50),
        ),
    ]
