# Generated by Django 3.0.3 on 2020-03-27 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ass_man', '0012_auto_20200225_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPCP',
            fields=[
                ('power_port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ass_man.Power_Port')),
                ('id_ref', models.PositiveIntegerField(blank=True)),
                ('asset_cp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ass_man.Asset')),
                ('cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cp.ChangePlan')),
            ],
            bases=('ass_man.power_port',),
        ),
        migrations.CreateModel(
            name='NPCP',
            fields=[
                ('network_port_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ass_man.Network_Port')),
                ('id_ref', models.PositiveIntegerField(blank=True)),
                ('conn_cp_id', models.PositiveIntegerField(blank=True)),
                ('asset_cp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ass_man.Asset')),
                ('cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cp.ChangePlan')),
            ],
            bases=('ass_man.network_port',),
        ),
        migrations.CreateModel(
            name='AssetCP',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ass_man.Asset')),
                ('id_ref', models.PositiveIntegerField(blank=True)),
                ('cp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cp.ChangePlan')),
            ],
            bases=('ass_man.asset',),
        ),
    ]
