# Generated by Django 3.0.3 on 2020-03-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0012_auto_20200225_1918'),
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeplan',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Datacenter'),
        ),
    ]
