# Generated by Django 3.0.3 on 2020-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeplan',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
