# Generated by Django 3.0.3 on 2020-03-30 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0016_merge_20200328_2230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp', '0002_changeplan_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_man.Model'),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ass_man.Rack'),
        ),
    ]
