# Generated by Django 3.0.3 on 2020-03-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_changeplan_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='id_ref',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npcp',
            name='conn_cp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npcp',
            name='id_ref',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ppcp',
            name='id_ref',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
