# Generated by Django 3.0.3 on 2020-04-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass_man', '0022_auto_20200413_1135'),
        ('cp', '0003_auto_20200330_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcp',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Rack'),
        ),
        migrations.AlterField(
            model_name='assetcp',
            name='rack_u',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
