# Generated by Django 3.0.3 on 2020-03-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20200327_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npcp',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='ppcp',
            name='cp',
        ),
    ]
