# Generated by Django 3.0.3 on 2020-03-28 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ass_man', '0016_merge_20200328_2230'),
        ('cp', '0004_auto_20200328_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcp',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='npcp',
            name='network_port_ptr',
        ),
        migrations.RemoveField(
            model_name='ppcp',
            name='power_port_ptr',
        ),
        migrations.AddField(
            model_name='assetcp',
            name='asset_number',
            field=models.PositiveIntegerField(blank=True, default=100000),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Datacenter'),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcp',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcp',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcp',
            name='rack',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ass_man.Rack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetcp',
            name='rack_u',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npcp',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Asset'),
        ),
        migrations.AddField(
            model_name='npcp',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ass_man.Network_Port'),
        ),
        migrations.AddField(
            model_name='npcp',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npcp',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='npcp',
            name='name',
            field=models.CharField(blank=True, default='mgmt', max_length=15),
        ),
        migrations.AddField(
            model_name='ppcp',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ass_man.Asset'),
        ),
        migrations.AddField(
            model_name='ppcp',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ppcp',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ppcp',
            name='pdu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ass_man.PDU'),
        ),
        migrations.AddField(
            model_name='ppcp',
            name='port_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='npcp',
            name='asset_cp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp.AssetCP'),
        ),
        migrations.AlterField(
            model_name='npcp',
            name='conn_cp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp.NPCP'),
        ),
        migrations.AlterField(
            model_name='ppcp',
            name='asset_cp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp.AssetCP'),
        ),
    ]
